baseURL = "https://evelynrosepark.com/"
languageCode = "en-us"
title = "Evelyn Park"
theme = "github-style"
#googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Evelyn Park"
  description = "Athropologist with interests in FOSS, folklore, linguistics, medieval studies, and Hebrew Bible scholarship."
  github = "evelynrp"
#  facebook = "MeiK2333"
#  twitter = "MeiK2333"
#  linkedin = "MeiK2333"
#  instagram = "MeiK2333"
#  tumblr = "MeiK2333"
  email = "evelynpark@disroot.org"
  url = "https://evelynrosepark.com/"
#  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  avatar = "/images/BhjFlag_Transgender.svg"
  headerIcon = "/images/GitHub-Mark-Light-32px.png"
  location = "United States"
#  userStatusEmoji = "ğŸ˜€"
#  enableGitalk = true

#  [params.gitalk]
#    clientID = "Your client ID" # Your client ID
#    clientSecret = "Your client secret" # Your client secret
#    repo = "LuvSia" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
#    owner = "ventusoon" # æ‚¨çš„GitHub ID
#    admin = "ventusoon" # æ‚¨çš„GitHub ID
#    id = "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
#    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
#    perPage = 15 # Pagination size, with maximum 100.
#    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
#    createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
#    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.
#    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†
  [[params.links]]
    title = "Website"
    href = "https://evelynrosepark.com/"
  [[params.links]]
    title = "Discord"
    href = "https://discord.com/users/1025102936512143403"
    icon = "images/discord.png"
  [[params.links]]
    title = "Session"
    href = "images/session-id.svg"
    icon = "images/session.png"
  [[params.links]]
    title = "XMPP"
    href = "mailto:evelynpark@disroot.org"
    icon = "images/conversations.png"
  [[params.links]]
    title = "Signal"
    href = "https://signal.me/#eu/-Cfc84TPyTXCToImeJ5Rgtdz6DPqL8NDgp03PnA4YhOSJelmaadK85IKJ5AW-vDV/"
    icon = "images/signal.svg"
  [[params.links]]
    title = "Facebook"
    href = "https://www.facebook.com/profile.php?id=61556589003356"
    icon = "images/facebook.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
